title: "Buttons"
description: |
  Buttons are to be used accross the website to link to other pages and or sections.

patterns:
  basic:
    title: "Primary Button"
    description:  |
      The primary button is to be used on any light background.
    fields:
      - name: linkName
        type: string
        example: "Apply Now"
      - name: buttonLink
        type: string
        example: "/job-postings"
  ghost:
    title: "Secondary Nutton"
    description:  |
      The Secondary Ghost Button is to be used when the link needs to stand out from the rest.
    fields:
      - name: linkName
        type: string
        example: "Apply Now"
      - name: buttonLink
        type: string
        example: "/job-postings"
  light-button:
    title: "Light Button"
    description:  |
      The Light Button is used on dark backgrounds when the Primary Button does not offer enough contrast.
    fields:
      - name: linkName
        type: string
        example: "Apply Now"
      - name: buttonLink
        type: string
        example: "/job-postings"
