title: "Cards"
description: |
  Cards are created to display grouped content of different objects. It usually leads to another page pr overlay with a detailed description of the card. The cards maybe vertical or horizontal.

patterns:
  basic-cards:
    title: "Basic Card"
    description: |
      Card for displaying important horizontal content. It can be used in homepage.
    fields:
      - name: image
        type: image
        example: "/images/red-melon-logo-colour.png"
      - name: brandName
        type: string
        example: "Red Melonn"
      - name: position
        type: string
        example: "Graphic Design Intern"
      - name: linkName
        type: string
        example: "Apply Now"
      - name: buttonLink
        type: string
        example: "/job-listings"
  job-postings:
    title: "Job Postings Card"
    description: |
      Card to present job posting information.
    fields:
      - name: company
        type: string
        example: "Agency"
      - name: position
        type: string
        example: "Art director"
      - name: duration
        type: string
        example: "4 months"
      - name: location
        type: string
        example: "Ottawa, Ontario"
      - name: daysLeft
        type: string
        example: "6 days left"
  job-bookmarks:
    title: "Bookmarked Job Posting Card"
    description: |
      These cards display a bookmarked job posting.
  application-status-card:
    title: "Application Status Card"
    description: |
      These cards display the point at which your application is with different companies.
  employer-postings:
    title: "Employer Posting"
    description: |
      A card to show employers which of their jobs are posted on the board.
  job-description:
    title: "Job Description"
    description: |
      A card that shows the job description when the posting is clicked.
  job-application:
    title: "Job Application"
    description: |
      A card to show employers all the applicants that have applied for their posting.
  email-overlay:
    title: "Email Overlay"
    description: |
      A messaging system that appears when an employer wants to get in contact with an applicant.
  student-profile-overlay:
    title: "Student Profile Overlay"
    description: |
      When an employer wants to learn more about a candidate, this appears when their application card is clicked on to show their profile.
